index:
    path: /
    controller: App\Controller\DefaultController::index

login:
  path: /security/login
  defaults: { _controller: 'App\Controller\SecurityController::login' }

interest:
  path: /interest
  defaults: { _controller: 'App\Controller\InterestCategoryController::interest' }

register:
  path: /register
  defaults: { _controller: 'App\Controller\RegistrationController::register' }


category:
  path: /category/index
  defaults: { _controller: 'App\Controller\CategoryController::index' }

product_by_category:
  path: /product/{id}
  defaults: { _controller: 'App\Controller\ProductController::show' }

all_product:
  path: /all
  defaults: { _controller: 'App\Controller\ProductController::showAll' }

show_product:
  path: /product
  defaults: { _controller: 'App\Controller\ProductController:showProduct'}

