index:
    path: /
    controller: App\Controller\DefaultController::index

login:
  path: /security/login
  defaults: { _controller: 'App\Controller\SecurityController::login' }

app_logout:
  path: /logout

interest:
  path: /interest/{id}
  defaults: { _controller: 'App\Controller\UserController::addCategoryToFavoritesInterest' }

register:
  path: /register
  defaults: { _controller: 'App\Controller\RegistrationController::register' }

product_by_category:
  path: /product/{id}
  defaults: { _controller: 'App\Controller\ProductController::show' }

all_product:
  path: /all
  defaults: { _controller: 'App\Controller\ProductController::showAll' }

show_product:
  path: /target/{id}
  defaults: { _controller: 'App\Controller\ProductController:showProduct'}

show_by_interest:
  path: /myinterest
  defaults: { _controller: 'App\Controller\ProductController:showProductByInterest'}


